apiVersion: v1
kind: Service
metadata:
  name: bank-app
spec:
  type: NodePort
  selector:
    app: bank-app
  ports:
    - port: 80
      targetPort: 5000

# production would use LoadBalancer/Ingress instead of NodePort