replicaCount: 1

image:
  repository: astraluniverse/bank-app-cd
  tag: "latest"
  pullPolicy: Always

service:
  nodePort: 32172

mysql:
  enabled: true
  image: "mysql:8.0"
  database: bank
  user: bankuser
  password: bankpass
  rootPassword: rootpass
  storage:
    size: 2Gi
    storageClassName: ""   # leave empty to use cluster default
