apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app
spec:
  replicas: {{ .Values.replicaCount }}  # must be 1 for sqlite db
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
        - name: bank-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000

# install: helm install bank-app ./helm/bank-app
# upgrade: helm upgrade bank-app ./helm/bank-app
# uninstall: helm uninstall bank-app
# check pod: kubectl get pods
# get node port: kubectl get svc bank-app
# access app: http://<NodeIP>:<NodePort>