{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bank-app-cd.fullname" . }}-mysql
type: Opaque
stringData:
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
{{- end }}
