apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-app-cd.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "bank-app-cd.name" . }}
  ports:
    - port: 80
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}
