name: CI

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        if: env.SNYK_TOKEN != ''
        run: npm install -g snyk

      - name: Snyk auth
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        if: env.SNYK_TOKEN != ''
        run: snyk auth $SNYK_TOKEN

      - name: Snyk scan (Python deps)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        if: env.SNYK_TOKEN != ''
        working-directory: bank_website/backend
        run: snyk test

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./Dockerfile

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false 
          tags: bank-app:ci-temp

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bank-app:ci-temp
          format: table
          ignore-unfixed: true

      - name: Run smoke test
        run: |
          docker run -d --name test bank-app:ci-temp
          sleep 5
          docker logs test || true
          docker stop test || true

      - name: Push final image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bank-app:latest
            ${{ secrets.DOCKER_USERNAME }}/bank-app:${{ github.sha }}


